import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        style={{           
          backgroundImage: "url('/images/Fondo.jpg')", // Asegúrate de tener esta imagen en tu carpeta public/images
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundAttachment: "fixed", // Para efecto parallax
          backgroundRepeat: "no-repeat",
        }}
      >
        
        {children}
      </body>
    </html>
  );
}
